#!/usr/bin/with-contenv sh
set -e
set +x

CONSUL_URL=${CONSUL_URL:-consul.service.consul:8500}
FILECONSUL_DC=${FILECONSUL_DC:-dc1}

if [ -z "$CONSUL_URL" ]; then
  echo "CONSUL_URL environment variable must be set."
  exit 0
fi

if [ -z "$FILECONSUL_PREFIX" ]; then
  echo "FILECONSUL_PREFIX environment variable must be set."
  exit 0
fi

if [ -z "$FILECONSUL_BASEPATH" ]; then
  echo "FILECONSUL_BASEPATH environment variable must be set."
  exit 0
fi

# Check consul status
status=`fileconsul status --addr $CONSUL_URL --prefix $FILECONSUL_PREFIX --dc $FILECONSUL_DC --basepath $FILECONSUL_BASEPATH 2>&1`
echo "$status"
if [ -n "$status" ]; then
    # Pull changes
    pull=`fileconsul pull --addr $CONSUL_URL --prefix $FILECONSUL_PREFIX --dc $FILECONSUL_DC --basepath $FILECONSUL_BASEPATH 2>&1`
    echo "$pull"
fi
exit 0